# Generated by Django 2.1.2 on 2018-11-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkings',
            name='isOccupied',
            field=models.BooleanField(default=False),
        ),
    ]
