# Generated by Django 2.1.2 on 2018-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_parkings_isocupated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
