# Generated by Django 2.1.2 on 2018-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0005_auto_20181107_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkings',
            name='x',
        ),
        migrations.RemoveField(
            model_name='parkings',
            name='y',
        ),
        migrations.AddField(
            model_name='parkings',
            name='br_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkings',
            name='br_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkings',
            name='tl_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkings',
            name='tl_y',
            field=models.IntegerField(default=0),
        ),
    ]
